name: Release please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .config/release-please-config.json
          manifest-file: .config/.release-please-manifest.json

      - name: Checkout Code
        if: steps.release.outputs.release_created
        uses: actions/checkout@v4

      - name: Remove the CHANGELOG.md file
        if: steps.release.outputs.release_created
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git rm CHANGELOG.md
          git commit -m "chore: Remove CHANGELOG.md"
          git push origin main

      - name: Trigger release workflow
        if: steps.release.outputs.release_created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run release.yml --ref main
